Remove deprecated headers.
ros/pluginlib pull request #217
Opened 2021-05-14 23:27 UTC by clalancette

They have been deprecated since 2017, so I think it is long
past time to remove them.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

2021-05-20 19:23 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14673)](http://ci.ros2.org/job/ci_linux/14673/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9425)](http://ci.ros2.org/job/ci_linux-aarch64/9425/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12336)](http://ci.ros2.org/job/ci_osx/12336/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14816)](http://ci.ros2.org/job/ci_windows/14816/)

2021-05-24 16:29 UTC, ahcorde requested changes
There are some warnings in MacOS. https://ci.ros2.org/job/ci_osx/12336/clang/new/.

2021-05-24 18:10 UTC, clalancette commented
> There are some warnings in MacOS. https://ci.ros2.org/job/ci_osx/12336/clang/new/.

Ah yeah, those are unrelated and are fixed by https://github.com/ros-perception/image_common/pull/192

2021-05-24 18:15 UTC, ahcorde approved these changes

2021-05-24 18:43 UTC, merged